### ISSUE TITLE
Help: Compile Error

### ISSUE THREAD

**Issue by rainer1108** [splendidinternet/Magento2_German_LocalePack_de_DE#23] opened 2016-05-31 05:39 UTC
..magento setup:di:compile

I recive a comiler error ( Magento ver. 2.0.7.).

Any ideas?

**Comment by niclashoyer** [comment] 2016-06-01 14:04
Can you post the error here? A rough guest: do you use PHP 5.5? Maybe PHP 5.6 works.

**Comment by christophbee** [comment] 2016-09-19 12:36
I have also a compilation error in my custom theme that is dependent von the blank theme. 
Running the command "php bin/magento setup:static-content:deploy de_DE" --> no errors in blank or luma theme. But when my custom theme is compiled I get the following error:

  [Magento\Framework\View\Asset\ContentProcessorException]     
  Compilation from source:                                     
  frontend/[namespace]/[theme]/de_DE/css/email-fonts.less  
  Compilation from source:                                     
  frontend/[namespace]/[theme]/de_DE/css/email-fonts.less 

The error also occurs when I comment out the complete content of the email-fonts.less 

Any idea what's going wrong there?

**Comment by niclashoyer** [comment] 2017-01-05 14:42
Your problems do not seem to be related to the German translations. Closing for now. It could be an error in your LESS file. Magento 2 sometimes just throws error messages away, so you won't see the cause.

**Closed by niclashoyer** 2017-01-05 14:42 UTC
