### ISSUE TITLE
Checkout has huge translation issues

### ISSUE THREAD

**Issue by grasdaggel** [splendidinternet/Magento2_German_LocalePack_de_DE#25] opened 2016-06-15 08:53 UTC
The following line:

`Please enter a valid email address (Ex: johndoe@domain.com).,Bitte geben Sie eine gültige E-Mail-Adresse ein (z.B: johndoe@domain.com).`

does not translate in Magento 2.0.4. Anyone is having the same issue? You can trigger it by processing the checkout and enter an non-mail-string into the Mail field.

**Comment by riker09** [comment] 2016-07-20 07:09
I can confirm this behaviour.

![checkout](https://cloud.githubusercontent.com/assets/568497/16977945/7b7c7832-4e59-11e6-8987-8a78952d2c08.png)

**Comment by niclashoyer** [comment] 2017-01-05 14:40
Hm, this translation is in the CSV since 1.0.0, it seems there is another bug in Magento 2.

**Comment by privatereese** [comment] 2017-04-11 12:12
Is this fixed now? Or does someone know where to search for the bug? This and all emails are not correctly translated at my site on magento 2.1.5

**Comment by niclashoyer** [comment] 2017-04-11 12:15
I just found the issue at magento 2: https://github.com/magento/magento2/issues/4883

It seems the translate function is not called and thus the string is not translated. There is a workaround mentioned at [the bottom](https://github.com/magento/magento2/issues/4883#issuecomment-285018521)

**Comment by niclashoyer** [comment] 2017-04-11 12:16
also FYI:

> Fix will be delivered in 2.1.7, 2.0.15 and 2.2.0

**Comment by privatereese** [comment] 2017-04-11 14:04
Is this the same error that leaves emails untranslated?

**Comment by MichaelKahl** [comment] 2017-10-20 10:32
in 2.2.0 behoben

**Closed by MichaelKahl** 2017-10-20 10:32 UTC
Labels: bug, cantfix
