### ISSUE TITLE
Couldn't get available versions for package splendidinternet/mage2-locale-de-de

### ISSUE THREAD

**Issue by shofer** [splendidinternet/Magento2_German_LocalePack_de_DE#42] opened 2016-08-31 13:32 UTC
If i open the setup page and click to compoments i get a 500 error (loading spinner is running forever)

Magento 2.1.0 and 2.1.1

/setup/index.php/componentGrid/components

> An error occurred during execution; please try again later.
> 
> Additional information:
> 
> RuntimeException
> 
> File:
> /home/shop/web/setup/src/Magento/Setup/Model/PackagesData.php:88
> Message:
> Couldn't get available versions for package splendidinternet/mage2-locale-de-de
> Stack trace:
> # 0 /home/shop/web/setup/src/Magento/Setup/Controller/ComponentGrid.php(98): Magento\Setup\Model\PackagesData->syncPackagesData()
> # 1 /home/shop/web/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\ComponentGrid->componentsAction()
> # 2 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
> # 3 /home/shop/web/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
> # 4 /home/shop/web/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
> # 5 /home/shop/web/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
> # 6 /home/shop/web/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
> # 7 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
> # 8 /home/shop/web/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
> # 9 /home/shop/web/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
> # 10 /home/shop/web/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
> # 11 /home/shop/web/setup/index.php(31): Zend\Mvc\Application->run()
> # 12 {main}

can somebody reproduce this problem?

**Comment by TobiasJ** [comment] 2016-11-10 13:11
Same issue here, did you manage to solve it?

**Comment by cadacual** [comment] 2016-11-14 15:11
Same issue here too

**Comment by lucaspozzi** [comment] 2016-12-06 01:34
The problem is with the magento marketplace.
Try your url setup/index.php/componentGrid/components
If I log out of the marketplace, I get a nice json.
If I am logged in, I guess a vendor I use both in the marketplace and from packagist causes the error.

I managed to keep everything else working after logging out of the marketplace.

**Comment by niclashoyer** [comment] 2016-12-11 22:16
A fix for this issue is in the develop branch, but it seems that it is not released yet:

https://github.com/magento/magento2/issues/6718

**Comment by niclashoyer** [comment] 2017-10-23 09:08
This should be resolved with Magento 2.2, we'll try to reproduce now.

**Comment by niclashoyer** [comment] 2017-10-23 09:10
We can't reproduce this on 2.2

**Closed by niclashoyer** 2017-10-23 09:10 UTC
Labels: bug, cantfix
